# Generated by Django 2.1.5 on 2019-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report_item',
            name='text',
            field=models.BooleanField(default=False),
        ),
    ]
