# Generated by Django 2.1.5 on 2019-01-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20190127_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(default=True)),
                ('f02588', models.FloatField(null=True)),
                ('f02589', models.FloatField(null=True)),
                ('f02590', models.FloatField(null=True)),
                ('f02591', models.FloatField(null=True)),
                ('f02592', models.FloatField(null=True)),
                ('f02593', models.FloatField(null=True)),
                ('f02594', models.FloatField(null=True)),
                ('f02595', models.FloatField(null=True)),
                ('f02596', models.FloatField(null=True)),
                ('f02597', models.FloatField(null=True)),
                ('f02598', models.FloatField(null=True)),
                ('f02599', models.FloatField(null=True)),
                ('f02600', models.FloatField(null=True)),
                ('f02601', models.FloatField(null=True)),
                ('f02602', models.FloatField(null=True)),
                ('f02603', models.FloatField(null=True)),
                ('f02604', models.FloatField(null=True)),
                ('total_fields', models.FloatField(null=True)),
                ('entered_fields', models.FloatField(null=True)),
                ('pending_fields', models.FloatField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('marked_fields', models.FloatField(null=True)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Account')),
            ],
            options={
                'db_table': 'PLAN',
            },
        ),
        migrations.AlterField(
            model_name='classification',
            name='index',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='report_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Classification'),
        ),
        migrations.AddField(
            model_name='plan',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Classification'),
        ),
        migrations.AddField(
            model_name='plan',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Classification'),
        ),
        migrations.AddField(
            model_name='plan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_task', to='Backend.Task'),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Classification'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('company', 'report_period', 'year', 'report_type', 'report_name')},
        ),
    ]
