# Generated by Django 2.1.5 on 2019-01-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20190127_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Task'),
        ),
    ]
