# Generated by Django 2.1.5 on 2019-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20190131_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f02584',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtnh',
            name='f00558',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttsx',
            name='f02587',
            field=models.FloatField(null=True),
        ),
    ]
