# Generated by Django 2.1.5 on 2019-02-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20190214_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02622',
            field=models.FloatField(null=True),
        ),
    ]
