# Generated by Django 2.1.5 on 2019-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_bssx_f02622'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02625',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bssx',
            name='f02626',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtsx',
            name='f02624',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttnh',
            name='f02623',
            field=models.FloatField(null=True),
        ),
    ]
