# Generated by Django 2.1.5 on 2019-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_auto_20190227_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02629',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttnh',
            name='f02630',
            field=models.FloatField(null=True),
        ),
    ]
