# Generated by Django 2.1.5 on 2019-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20190307_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02634',
            field=models.FloatField(null=True),
        ),
    ]
