# Generated by Django 2.1.5 on 2019-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_bssx_f02634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02635',
            field=models.FloatField(null=True),
        ),
    ]
