# Generated by Django 2.1.5 on 2019-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_bpck_f02635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02636',
            field=models.FloatField(null=True),
        ),
    ]
