# Generated by Django 2.1.5 on 2019-03-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_cfttnh_f02636'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_change',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Task'),
            preserve_default=False,
        ),
    ]
