# Generated by Django 2.1.5 on 2019-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_item_change_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02637',
            field=models.FloatField(null=True),
        ),
    ]
