# Generated by Django 2.1.7 on 2019-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_cfgtsx_f02637'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02638',
            field=models.FloatField(null=True),
        ),
    ]
