# Generated by Django 2.1.7 on 2019-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_cfgtsx_f02638'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02639',
            field=models.FloatField(null=True),
        ),
    ]
