# Generated by Django 2.1.7 on 2019-03-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_cfgtsx_f02639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f02640',
            field=models.FloatField(null=True),
        ),
    ]
