# Generated by Django 2.1.7 on 2019-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_bsnh_f02640'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpnh',
            name='f02641',
            field=models.FloatField(null=True),
        ),
    ]
