# Generated by Django 2.1.7 on 2019-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_bpnh_f02641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02642',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttnh',
            name='f02643',
            field=models.FloatField(null=True),
        ),
    ]
