# Generated by Django 2.1.7 on 2019-03-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_auto_20190325_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02644',
            field=models.FloatField(null=True),
        ),
    ]
