# Generated by Django 2.1.7 on 2019-04-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_cfgtck_f02644'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02645',
            field=models.FloatField(null=True),
        ),
    ]
