# Generated by Django 2.1.7 on 2019-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_cfgtsx_f02645'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02646',
            field=models.FloatField(null=True),
        ),
    ]
