# Generated by Django 2.1.7 on 2019-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_cfgtsx_f02646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02647',
            field=models.FloatField(null=True),
        ),
    ]
