# Generated by Django 2.1.7 on 2019-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_cfttnh_f02647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02648',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtsx',
            name='f02649',
            field=models.FloatField(null=True),
        ),
    ]
