# Generated by Django 2.1.7 on 2019-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_auto_20190418_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02650',
            field=models.FloatField(null=True),
        ),
    ]
