# Generated by Django 2.1.7 on 2019-04-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0028_cfgtsx_f02650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02651',
            field=models.FloatField(null=True),
        ),
    ]
