# Generated by Django 2.1.7 on 2019-04-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0029_cfgtsx_f02651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02652',
            field=models.FloatField(null=True),
        ),
    ]
