# Generated by Django 2.1.7 on 2019-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_cfgtsx_f02652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpnh',
            name='f02653',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bpnh',
            name='f02654',
            field=models.FloatField(null=True),
        ),
    ]
