# Generated by Django 2.1.7 on 2019-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0031_auto_20190426_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02655',
            field=models.FloatField(null=True),
        ),
    ]
