# Generated by Django 2.1.7 on 2019-05-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0032_cfgtsx_f02655'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02656',
            field=models.FloatField(null=True),
        ),
    ]
