# Generated by Django 2.1.7 on 2019-05-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_cfgtsx_f02656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02657',
            field=models.FloatField(null=True),
        ),
    ]
