# Generated by Django 2.1.7 on 2019-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_cfgtsx_f02657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity',
            field=models.CharField(max_length=100),
        ),
    ]
