# Generated by Django 2.1.7 on 2019-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_auto_20190507_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02658',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtck',
            name='f02659',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtck',
            name='f02660',
            field=models.FloatField(null=True),
        ),
    ]
