# Generated by Django 2.1.7 on 2019-05-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0036_auto_20190521_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f02661',
            field=models.FloatField(null=True),
        ),
    ]
