# Generated by Django 2.1.7 on 2019-05-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0037_bsnh_f02661'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02662',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtck',
            name='f02663',
            field=models.FloatField(null=True),
        ),
    ]
