# Generated by Django 2.1.7 on 2019-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0038_auto_20190527_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02664',
            field=models.FloatField(null=True),
        ),
    ]
