# Generated by Django 2.1.7 on 2019-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0040_auto_20190606_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02667',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtsx',
            name='f02668',
            field=models.FloatField(null=True),
        ),
    ]
