# Generated by Django 2.1.7 on 2019-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0041_auto_20190610_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02669',
            field=models.FloatField(null=True),
        ),
    ]
