# Generated by Django 2.1.7 on 2019-06-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0042_cfgtck_f02669'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02670',
            field=models.FloatField(null=True),
        ),
    ]
