# Generated by Django 2.1.7 on 2019-06-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0043_cfttnh_f02670'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtnh',
            name='f02671',
            field=models.FloatField(null=True),
        ),
    ]
