# Generated by Django 2.1.7 on 2019-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0044_cfgtnh_f02671'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02672',
            field=models.FloatField(null=True),
        ),
    ]
