# Generated by Django 2.1.7 on 2019-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0045_cfgtck_f02672'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02673',
            field=models.FloatField(null=True),
        ),
    ]
