# Generated by Django 2.1.7 on 2019-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0046_bssx_f02673'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02674',
            field=models.FloatField(null=True),
        ),
    ]
