# Generated by Django 2.1.7 on 2019-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0047_cfgtsx_f02674'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttsx',
            name='f02675',
            field=models.FloatField(null=True),
        ),
    ]
