# Generated by Django 2.1.7 on 2019-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0048_cfttsx_f02675'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttbh',
            name='f02676',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02677',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02678',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02679',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02680',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02681',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02682',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02683',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02684',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02685',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02686',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02687',
            field=models.FloatField(null=True),
        ),
    ]
