# Generated by Django 2.1.7 on 2019-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0049_auto_20190712_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02688',
            field=models.FloatField(null=True),
        ),
    ]
