# Generated by Django 2.1.7 on 2019-07-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0050_cfgtsx_f02688'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsck',
            name='f02689',
            field=models.FloatField(null=True),
        ),
    ]
