# Generated by Django 2.1.7 on 2019-07-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0051_bsck_f02689'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsck',
            name='f02690',
            field=models.FloatField(null=True),
        ),
    ]
