# Generated by Django 2.1.7 on 2019-07-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0052_bsck_f02690'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02691',
            field=models.FloatField(null=True),
        ),
    ]
