# Generated by Django 2.1.7 on 2019-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0053_bpck_f02691'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02692',
            field=models.FloatField(null=True),
        ),
    ]
