# Generated by Django 2.1.7 on 2019-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0054_cfgtsx_f02692'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsck',
            name='f02693',
            field=models.FloatField(null=True),
        ),
    ]
