# Generated by Django 2.1.7 on 2019-08-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0055_bsck_f02693'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02694',
            field=models.FloatField(null=True),
        ),
    ]
