# Generated by Django 2.1.7 on 2019-08-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0056_cfgtck_f02694'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02695',
            field=models.FloatField(null=True),
        ),
    ]
