# Generated by Django 2.1.7 on 2019-08-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0057_bssx_f02695'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02696',
            field=models.FloatField(null=True),
        ),
    ]
