# Generated by Django 2.1.7 on 2019-08-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0058_cfgtsx_f02696'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02697',
            field=models.FloatField(null=True),
        ),
    ]
