# Generated by Django 2.1.7 on 2019-08-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0059_cfgtck_f02697'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsbh',
            name='f02698',
            field=models.FloatField(null=True),
        ),
    ]
