# Generated by Django 2.1.7 on 2019-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0060_bsbh_f02698'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02699',
            field=models.FloatField(null=True),
        ),
    ]
