# Generated by Django 2.1.7 on 2019-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0061_bssx_f02699'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02700',
            field=models.FloatField(null=True),
        ),
    ]
