# Generated by Django 2.1.7 on 2019-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0062_bssx_f02700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttsx',
            name='f02701',
            field=models.FloatField(null=True),
        ),
    ]
