# Generated by Django 2.1.7 on 2019-08-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0063_cfttsx_f02701'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttsx',
            name='f02702',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttsx',
            name='f02703',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttsx',
            name='f02704',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttsx',
            name='f02705',
            field=models.FloatField(null=True),
        ),
    ]
