# Generated by Django 2.1.7 on 2019-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0064_auto_20190809_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsbh',
            name='f02706',
            field=models.FloatField(null=True),
        ),
    ]
