# Generated by Django 2.1.7 on 2019-08-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0065_bsbh_f02706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02707',
            field=models.FloatField(null=True),
        ),
    ]
