# Generated by Django 2.1.7 on 2019-08-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0066_cfgtck_f02707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttbh',
            name='f02708',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02709',
            field=models.FloatField(null=True),
        ),
    ]
