# Generated by Django 2.1.7 on 2019-08-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0067_auto_20190821_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02710',
            field=models.FloatField(null=True),
        ),
    ]
