# Generated by Django 2.1.7 on 2019-09-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0068_bpck_f02710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02711',
            field=models.FloatField(null=True),
        ),
    ]
