# Generated by Django 2.1.7 on 2019-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0070_cfgtsx_f02712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02713',
            field=models.FloatField(null=True),
        ),
    ]
