# Generated by Django 2.1.7 on 2019-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0071_bpck_f02713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02714',
            field=models.FloatField(null=True),
        ),
    ]
