# Generated by Django 2.1.7 on 2019-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0072_bpck_f02714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02715',
            field=models.FloatField(null=True),
        ),
    ]
