# Generated by Django 2.1.7 on 2019-09-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0073_cfgtck_f02715'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02716',
            field=models.FloatField(null=True),
        ),
    ]
