# Generated by Django 2.1.7 on 2019-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0074_bssx_f02716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02717',
            field=models.FloatField(null=True),
        ),
    ]
