# Generated by Django 2.1.7 on 2019-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0075_cfgtck_f02717'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f02718',
            field=models.FloatField(null=True),
        ),
    ]
