# Generated by Django 2.1.7 on 2019-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0076_cfttnh_f02718'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02719',
            field=models.FloatField(null=True),
        ),
    ]
