# Generated by Django 2.1.7 on 2019-09-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0077_bssx_f02719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpck',
            name='f02720',
            field=models.FloatField(null=True),
        ),
    ]
