# Generated by Django 2.1.7 on 2019-10-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0078_bpck_f02720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02721',
            field=models.FloatField(null=True),
        ),
    ]
