# Generated by Django 2.1.7 on 2019-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0079_cfgtsx_f02721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02722',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtsx',
            name='f02723',
            field=models.FloatField(null=True),
        ),
    ]
