# Generated by Django 2.1.7 on 2019-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0080_auto_20191010_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02724',
            field=models.FloatField(null=True),
        ),
    ]
