# Generated by Django 2.1.7 on 2019-10-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0081_bssx_f02724'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsbh',
            name='f02725',
            field=models.FloatField(null=True),
        ),
    ]
