# Generated by Django 2.1.7 on 2019-10-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0082_bsbh_f02725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02726',
            field=models.FloatField(null=True),
        ),
    ]
