# Generated by Django 2.1.7 on 2019-10-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0083_cfgtsx_f02726'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02727',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtsx',
            name='f02728',
            field=models.FloatField(null=True),
        ),
    ]
