# Generated by Django 2.1.7 on 2019-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0084_auto_20191016_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02729',
            field=models.FloatField(null=True),
        ),
    ]
