# Generated by Django 2.1.7 on 2019-10-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0085_bssx_f02729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02730',
            field=models.FloatField(null=True),
        ),
    ]
