# Generated by Django 2.1.7 on 2019-10-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0086_cfgtsx_f02730'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsck',
            name='f02731',
            field=models.FloatField(null=True),
        ),
    ]
