# Generated by Django 2.1.7 on 2019-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0087_bsck_f02731'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f02732',
            field=models.FloatField(null=True),
        ),
    ]
