# Generated by Django 2.1.7 on 2019-11-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0088_bsnh_f02732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02733',
            field=models.FloatField(null=True),
        ),
    ]
