# Generated by Django 2.1.7 on 2019-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0089_cfgtsx_f02733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02734',
            field=models.FloatField(null=True),
        ),
    ]
