# Generated by Django 2.1.7 on 2019-11-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0090_cfgtsx_f02734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(null=True)),
                ('waiting1_time', models.DateTimeField(null=True)),
                ('waiting2_time', models.DateTimeField(null=True)),
                ('approve_time', models.DateTimeField(null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Task_Log',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task_log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.Task', unique=True),
        ),
    ]
