# Generated by Django 3.0 on 2019-12-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0092_auto_20191206_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task_Log',
        ),
    ]
