# Generated by Django 3.0 on 2019-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0093_delete_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02735',
            field=models.FloatField(null=True),
        ),
    ]
