# Generated by Django 3.0 on 2020-01-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0094_cfgtsx_f02735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsck',
            name='f02736',
            field=models.FloatField(null=True),
        ),
    ]
