# Generated by Django 3.0 on 2020-01-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0095_bsck_f02736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttck',
            name='f02737',
            field=models.FloatField(null=True),
        ),
    ]
