# Generated by Django 3.0 on 2020-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0096_cfttck_f02737'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02738',
            field=models.FloatField(null=True),
        ),
    ]
