# Generated by Django 3.0 on 2020-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0097_cfgtck_f02738'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02740',
            field=models.FloatField(null=True),
        ),
    ]
