# Generated by Django 3.0 on 2020-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0098_cfgtsx_f02740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtck',
            name='f02741',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfgtck',
            name='f02742',
            field=models.FloatField(null=True),
        ),
    ]
