# Generated by Django 3.0 on 2020-06-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0099_auto_20200515_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttbh',
            name='f02743',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cfttbh',
            name='f02744',
            field=models.FloatField(null=True),
        ),
    ]
