# Generated by Django 3.0 on 2020-08-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0101_auto_20200618_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfgtsx',
            name='f02739',
            field=models.FloatField(null=True),
        ),
    ]
