# Generated by Django 3.0 on 2020-10-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0102_cfgtsx_f02739'),
    ]

    operations = [
        migrations.AddField(
            model_name='bssx',
            name='f02747',
            field=models.FloatField(null=True),
        ),
    ]
