# Generated by Django 3.1.2 on 2020-11-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0107_auto_20201108_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='display_type',
        ),
    ]
