# Generated by Django 3.1.2 on 2020-11-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0110_account_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('ref_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('highest_price', models.FloatField()),
                ('lowest_price', models.FloatField()),
                ('average_price', models.FloatField()),
                ('price_change', models.FloatField()),
                ('change_ratio', models.FloatField()),
                ('match_order_volume', models.FloatField()),
                ('match_order_value', models.FloatField()),
                ('put_through_volume', models.FloatField()),
                ('put_through_value', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('listed_volume', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.company')),
            ],
            options={
                'db_table': 'stock_price',
                'unique_together': {('stock_date', 'company')},
            },
        ),
    ]
