# Generated by Django 3.1.2 on 2020-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0111_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_price',
            name='average_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='change_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='price_change',
            field=models.FloatField(null=True),
        ),
    ]
