# Generated by Django 3.1.2 on 2020-11-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0112_auto_20201109_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('close_price', models.FloatField()),
                ('match_order_volume', models.FloatField()),
                ('match_order_value', models.FloatField()),
                ('best_buy_price', models.FloatField()),
                ('best_buy_volume', models.FloatField()),
                ('best_sell_price', models.FloatField()),
                ('best_sell_volume', models.FloatField()),
                ('buy_order_number', models.FloatField()),
                ('sell_order_number', models.FloatField()),
                ('buy_sell_number', models.FloatField()),
                ('buy_order_volume', models.FloatField()),
                ('sell_order_volume', models.FloatField()),
                ('buy_sell_volume', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.company')),
            ],
            options={
                'db_table': 'stock_order',
                'unique_together': {('stock_date', 'company')},
            },
        ),
    ]
