# Generated by Django 3.1.2 on 2020-11-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0113_stock_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreigner_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('room', models.FloatField()),
                ('ownership_ratio', models.FloatField()),
                ('room_remain_volume', models.FloatField()),
                ('room_remain_ratio', models.FloatField()),
                ('buy_volume', models.FloatField()),
                ('buy_market_volume', models.FloatField()),
                ('sell_volume', models.FloatField()),
                ('sell_market_volume', models.FloatField()),
                ('buy_value', models.FloatField()),
                ('buy_market_value', models.FloatField()),
                ('sell_value', models.FloatField()),
                ('sell_market_value', models.FloatField()),
                ('buy_sell_volume', models.FloatField()),
                ('buy_sell_value', models.FloatField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.company')),
            ],
            options={
                'db_table': 'foreigner_order',
                'unique_together': {('stock_date', 'company')},
            },
        ),
    ]
