# Generated by Django 3.1.2 on 2020-11-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0114_foreigner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('assign_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(null=True)),
                ('into_money', models.FloatField(null=True)),
                ('entry_time', models.DateTimeField(null=True)),
                ('waiting1_time', models.DateTimeField(null=True)),
                ('waiting2_time', models.DateTimeField(null=True)),
                ('approve_time', models.DateTimeField(null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.file')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('report_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
            ],
            options={
                'db_table': 'task_stock',
                'unique_together': {('stock_date', 'report_name')},
            },
        ),
    ]
