# Generated by Django 3.1.2 on 2020-11-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0117_auto_20201111_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounttype', to='Backend.classification'),
        ),
    ]
