# Generated by Django 3.1.2 on 2020-11-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0118_auto_20201112_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='function', to='Backend.classification'),
        ),
    ]
