# Generated by Django 3.1.2 on 2020-11-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0120_task_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_stock',
            name='data_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
