# Generated by Django 3.1.2 on 2020-11-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0123_remove_notification_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('refid', models.BigIntegerField()),
                ('content', models.TextField()),
                ('note', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('handle_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
            ],
            options={
                'db_table': 'violate',
            },
        ),
    ]
