# Generated by Django 3.1.2 on 2020-11-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0125_foreign_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foreigner_Order',
        ),
    ]
