# Generated by Django 3.1.2 on 2020-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0127_foreign_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_order',
            old_name='match_order_value',
            new_name='order_value',
        ),
        migrations.RenameField(
            model_name='stock_order',
            old_name='match_order_volume',
            new_name='order_volume',
        ),
        migrations.RenameField(
            model_name='stock_price',
            old_name='match_order_value',
            new_name='deal_value',
        ),
        migrations.RenameField(
            model_name='stock_price',
            old_name='match_order_volume',
            new_name='deal_volume',
        ),
        migrations.RenameField(
            model_name='stock_price',
            old_name='put_through_value',
            new_name='order_value',
        ),
        migrations.RenameField(
            model_name='stock_price',
            old_name='put_through_volume',
            new_name='order_volume',
        ),
    ]
