# Generated by Django 3.1.2 on 2020-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0128_auto_20201120_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_price',
            name='total_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_price',
            name='total_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='listed_volume',
            field=models.FloatField(null=True),
        ),
    ]
