# Generated by Django 3.1.2 on 2020-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0129_auto_20201120_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_related',
            name='ref',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
