# Generated by Django 3.1.2 on 2020-11-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0130_task_related_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_related',
            old_name='ref',
            new_name='task_prev',
        ),
    ]
