# Generated by Django 3.1.2 on 2020-11-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0131_auto_20201123_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help_comment',
            name='delete_reason',
        ),
        migrations.RemoveField(
            model_name='news_comment',
            name='delete_reason',
        ),
    ]
