# Generated by Django 3.1.2 on 2020-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0132_auto_20201124_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_code', models.CharField(max_length=5)),
                ('level1_detail', models.CharField(max_length=200)),
                ('level2_code', models.CharField(max_length=5)),
                ('level2_detail', models.CharField(max_length=200)),
                ('level3_code', models.CharField(max_length=5, unique=True)),
                ('level3_detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
    ]
