# Generated by Django 3.1.2 on 2020-12-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0134_company_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='level1_detail',
            new_name='level1_name',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='level2_detail',
            new_name='level2_name',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='level3_detail',
            new_name='level3_name',
        ),
    ]
