# Generated by Django 3.1.2 on 2020-12-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0135_auto_20201219_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
