# Generated by Django 3.1.2 on 2021-01-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0139_price_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_live',
            name='f02823',
        ),
    ]
