# Generated by Django 3.1.2 on 2021-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0140_remove_price_live_f02823'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accumulate',
            field=models.BooleanField(default=False),
        ),
    ]
