# Generated by Django 3.1.2 on 2021-01-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0141_task_accumulate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreign_deal',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_deal', to='Backend.company'),
        ),
        migrations.AlterField(
            model_name='foreign_order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_order', to='Backend.company'),
        ),
        migrations.AlterField(
            model_name='price_live',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_live', to='Backend.company'),
        ),
        migrations.AlterField(
            model_name='stock_order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_order', to='Backend.company'),
        ),
        migrations.AlterField(
            model_name='stock_price',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_price', to='Backend.company'),
        ),
    ]
