# Generated by Django 3.1.2 on 2021-03-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0143_auto_20210208_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f02955',
            field=models.FloatField(null=True),
        ),
    ]
