# Generated by Django 3.2 on 2021-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0144_bsnh_f02955'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_price',
            name='bv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='eps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='number_share',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pbi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pbm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pei',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='pem',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='valuation_pbi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='valuation_pbm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='valuation_pei',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='valuation_pem',
            field=models.FloatField(null=True),
        ),
    ]
