# Generated by Django 3.2.4 on 2021-06-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0146_auto_20210618_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_price',
            name='f02978',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_price',
            name='f02979',
            field=models.FloatField(null=True),
        ),
    ]
