# Generated by Django 3.2.6 on 2021-09-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0147_auto_20210628_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_price',
            name='f02981',
            field=models.FloatField(null=True),
        ),
    ]
