# Generated by Django 3.2.6 on 2022-03-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0151_auto_20220301_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfttnh',
            name='f03011',
            field=models.FloatField(null=True),
        ),
    ]
