# Generated by Django 3.2.6 on 2022-03-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0152_cfttnh_f03011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('ticker', models.JSONField()),
                ('expert', models.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.company')),
            ],
            options={
                'db_table': 'analysis_report',
            },
        ),
    ]
