# Generated by Django 3.2.6 on 2022-03-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0154_color_choice_color_scheme_data_type_filter_choice_filter_type_menu_choice_money_unit_placement_setti'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_report',
            name='content',
            field=models.TextField(default='xxx'),
            preserve_default=False,
        ),
    ]
