# Generated by Django 3.2.6 on 2022-03-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0156_rename_title_analysis_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_report',
            name='total_pages',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
