# Generated by Django 3.2.6 on 2022-03-26 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0158_auto_20220324_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_price',
            name='f02901',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02902',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02903',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02904',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02905',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02906',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02907',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02908',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02909',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02910',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02911',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02912',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02913',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02914',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02915',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02916',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02917',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02918',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02919',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02920',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02921',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02922',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02923',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02924',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02925',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02926',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02927',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02928',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02929',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02930',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02931',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02932',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02933',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02934',
        ),
        migrations.RemoveField(
            model_name='stock_price',
            name='f02935',
        ),
        migrations.CreateModel(
            name='Task_Taindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('assign_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(null=True)),
                ('into_money', models.FloatField(null=True)),
                ('entry_time', models.DateTimeField(null=True)),
                ('waiting1_time', models.DateTimeField(null=True)),
                ('waiting2_time', models.DateTimeField(null=True)),
                ('approve_time', models.DateTimeField(null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('data_file', models.TextField(blank=True, null=True)),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.file')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.account')),
                ('report_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.classification')),
            ],
            options={
                'db_table': 'task_taindex',
                'unique_together': {('stock_date', 'report_name')},
            },
        ),
        migrations.CreateModel(
            name='Taindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('f02921', models.FloatField(null=True)),
                ('f02901', models.FloatField(null=True)),
                ('f02902', models.FloatField(null=True)),
                ('f02903', models.FloatField(null=True)),
                ('f02904', models.FloatField(null=True)),
                ('f02905', models.FloatField(null=True)),
                ('f02906', models.FloatField(null=True)),
                ('f02907', models.FloatField(null=True)),
                ('f02908', models.FloatField(null=True)),
                ('f02909', models.FloatField(null=True)),
                ('f02910', models.FloatField(null=True)),
                ('f02911', models.FloatField(null=True)),
                ('f02912', models.FloatField(null=True)),
                ('f02913', models.FloatField(null=True)),
                ('f02914', models.FloatField(null=True)),
                ('f02915', models.FloatField(null=True)),
                ('f02916', models.FloatField(null=True)),
                ('f02917', models.FloatField(null=True)),
                ('f02918', models.FloatField(null=True)),
                ('f02919', models.FloatField(null=True)),
                ('f02920', models.FloatField(null=True)),
                ('f02932', models.FloatField(null=True)),
                ('f02933', models.FloatField(null=True)),
                ('f02934', models.FloatField(null=True)),
                ('f02935', models.FloatField(null=True)),
                ('f02923', models.FloatField(null=True)),
                ('f02924', models.FloatField(null=True)),
                ('f02925', models.FloatField(null=True)),
                ('f02926', models.FloatField(null=True)),
                ('f02927', models.FloatField(null=True)),
                ('f02928', models.FloatField(null=True)),
                ('f02929', models.FloatField(null=True)),
                ('f02930', models.FloatField(null=True)),
                ('f02931', models.FloatField(null=True)),
                ('f02922', models.FloatField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.company')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Backend.task_taindex')),
            ],
            options={
                'db_table': 'taindex',
                'unique_together': {('stock_date', 'company')},
            },
        ),
    ]
