# Generated by Django 3.2.6 on 2022-03-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0160_auto_20220326_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taindex',
            name='f02932',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02933',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02934',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02935',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02936',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02937',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02938',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02939',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02940',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02941',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02942',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02943',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02944',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02945',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02946',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02947',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02948',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02949',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02950',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02951',
        ),
        migrations.RemoveField(
            model_name='taindex',
            name='f02952',
        ),
    ]
