# Generated by Django 3.2.6 on 2022-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0161_auto_20220326_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='taindex',
            name='f02932',
            field=models.FloatField(null=True),
        ),
    ]
