# Generated by Django 3.2.6 on 2022-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0162_taindex_f02932'),
    ]

    operations = [
        migrations.AddField(
            model_name='taindex',
            name='f02933',
            field=models.FloatField(null=True),
        ),
    ]
