# Generated by Django 3.2.6 on 2022-03-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0163_taindex_f02933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taindex',
            name='f02933',
        ),
    ]
