# Generated by Django 3.1.14 on 2022-04-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0164_remove_taindex_f02933'),
    ]

    operations = [
        migrations.AddField(
            model_name='taindex',
            name='f02934',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02935',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02936',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02937',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02938',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02939',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02940',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02941',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02942',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02943',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02944',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02945',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02946',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02947',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02948',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02949',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02950',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02951',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taindex',
            name='f02952',
            field=models.FloatField(null=True),
        ),
    ]
