# Generated by Django 3.1.14 on 2022-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0165_auto_20220409_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsnh',
            name='f03012',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bsnh',
            name='f03013',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bsnh',
            name='f03014',
            field=models.FloatField(null=True),
        ),
    ]
